In [ ]:
# # Day 25 - Image Processing Concepts 🚀

# ## Topics Covered:
# - Image as matrix
# - RGB vs Grayscale
# - Kernel & Convolution
# - Pooling
# - Dropout concept

In [12]:
import numpy as np

# 5x5 fake image
img = np.random.randint(0, 255, (5,5))
print(img)

[[ 54 206 170  39 203]
 [ 53  67 173 179 140]
 [ 10 125  12  85  62]
 [208 205  26 246  18]
 [  9  69 246 147  33]]


In [14]:
R = 100
G = 150
B = 200

gray = (R + G + B) / 3

In [15]:
kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

In [16]:
import numpy as np

img = np.random.randint(0, 10, (5,5))

kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

result = 0

# Apply kernel on center
for i in range(3):
    for j in range(3):
        result += img[i][j] * kernel[i][j]

print("Result:", result)

Result: -7


In [17]:
block = np.array([
    [2, 8],
    [5, 3]
])

print("Max Pool:", block.max())

Max Pool: 8


In [18]:
arr = np.array([1, 2, 3, 4, 5])

mask = np.random.choice([0,1], size=arr.shape)

print(arr * mask)

[0 0 0 4 0]
